ExamenUX/config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  resources :categories
  resources :todos

  root 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ExamenUX/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ExamenUX/app/models/category.rb
class Category < ApplicationRecord
	has_many :todos, :dependent => :destroy
end

ExamenUX/app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :category
end

ExamenUX/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

ExamenUX/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ExamenUX/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show, :edit, :update, :destroy]

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @category.update(category_params)
			redirect_to @category
		else
			render 'edit'
		end
	end

	def destroy
    	@category = Category.find(params[:id])
		@category.destroy

		redirect_to categories_path
	end

	private
	def set_category
		@category = Category.find(params[:id])
	end

	def category_params
		params.require(:category).permit(:name)
	end
end

ExamenUX/app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_action :set_todo, only: [:show, :edit, :update, :destroy]

	def index
		@todos = Todo.all
	end

	def show
	end

	def edit
	end

	def new
		@todo = Todo.new
		@categories = Category.all
	end

	def create
		@todo = Todo.new(todo_params)

		if @todo.save
			redirect_to todos_path
		else
			render 'new'
		end
	end

	def update
		
		if @todo.update(todo_params)
			redirect_to @todo
		else
			render 'edit'
		end
	end

	def destroy
    	@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to todos_path
	end


	private
	def set_todo
		@todo = Todo.find(params[:id])
	end

	def todo_params
		params.require(:todo).permit(:category_id, :description, :level)
	end
end

ExamenUX/app/helpers/application_helper.rb
module ApplicationHelper
end

ExamenUX/app/helpers/categories_helper.rb
module CategoriesHelper
end

ExamenUX/app/helpers/todos_helper.rb
module TodosHelper
end

ExamenUX/app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ExamenUX/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

ExamenUX/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
  <h1>Categories <%= link_to '(New)', new_category_path %></h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3">Todos</th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <td>
          <%= link_to category do %>
            <%= category.name %>
          <% end %>
          <br>
          <%= link_to '(Delete)', category, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>

        <td>
          <ul>
            <% category.todos.each do |todo| %>
            <!-- <tr><strong>Category Name</strong><%= todo.category.name %></tr> -->
            <li>
              <strong>Description: </strong><%= todo.description %><br>
              <strong>Level: </strong><%= todo.level %>
            </li>
            <hr>
            <% end %>
          </ul>
          
        </td>

      </tr>
      <hr>
      <% end %>
    </tbody>
  </table>

  <br>

  
<% end %>

ExamenUX/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

ExamenUX/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Category Name:</strong>
	<%= @category.name %>
</p>
<p>
	<tbody>
		<% @category.todos.each do |todo| %>
			<!-- <tr><strong>Category Name</strong><%= todo.category.name %></tr> -->
			<tr><strong>Description: </strong><%= todo.description %></tr><br>
			<tr><strong>Level: </strong><%= todo.level %></tr>
			<hr>
		<% end %>
	</tbody>

</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', category_path %>

ExamenUX/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ExamenUX</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<nav class="navbar navbar-inverse bg-inverse">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<%= link_to "Todo List", root_path, class: "navbar-brand" %>
			</div>

			
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<li><%= link_to "Categories", categories_path %></li>
						<li><%= link_to "Todo", todos_path %></li>
						<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
						<!-- <li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li role="separator" class="divider"></li>
							</ul>
						</li> -->
					<% else %>
						<li><%= link_to "Sign Up", new_user_registration_path %></li>
						<li><%= link_to "Sign In", new_user_session_path %></li>
					<% end %>
				</ul>
			</div>
		</div><!-- /.container-fluid -->
	</nav>
	<%= yield %>
</body>
</html>

ExamenUX/app/views/todos/_form.html.erb
<div class="row">
	<div class="col-md-7 col-md-offset-2">
		<h4>New Todos</h4>

		<%= bootstrap_form_for @todo do |f| %>

		<div class="field">
			<%= f.select :category_id,
			options_from_collection_for_select(@categories, "id", "name", :todo_category_id)
			%>
		</div>

		<div class="field">
			<%= f.text_field :description, class: "form-control" %>
		</div>

		<div class="field">
			<%= f.number_field :level, id: :todo_level %>
		</div>

		<div class="actions">
			<%= f.submit %>
		</div>
		<% end %>
	</div>
</div>

ExamenUX/app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

ExamenUX/app/views/todos/index.html.erb
<div class="row">
	<div class="col-md-7 col-md-offset-2">
		<h2>Todos <%= link_to '(New)', new_todo_path %></h2>
		<% @todos.each do | todo | %>
		<p>
			Description: 
			<%= link_to todo do %>
				<%= todo.description %>
			<% end %>
          <%= link_to '(Delete)', todo, method: :delete, data: { confirm: 'Are you sure?' } %>
		<p>Category: <%= todo.category.name %></p>
		<p>Level: <%= todo.level %></p>
		<hr>
		<% end %>
	</div>


</div>

ExamenUX/app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

ExamenUX/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Description :</strong>
	<%= @todo.description %>
</p>
<p>
	<strong>Category Name:</strong>
	<%= @todo.category.name %>
</p>
<p>
	<strong>Level:</strong>
	<%= @todo.level %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', category_path %>